_format_version: "2.1"

services:
  - name: image-process-service
    url: http://35.202.61.156/image/process
  
  - name: image-generate-service
    url: http://35.202.61.156/image/generate
  
  - name: image-query-service
    url: http://35.202.61.156/image/query

  - name: image-inspect-service
    url: http://35.202.61.156/image/inspect

routes:
  - name: image-process-route
    paths:
      - /kong/image/process
    service: image-process-service
    plugins:
      - name: basic-auth
        config:
          hide_credentials: true
      # - name: rate-limiting
      #   config:
      #     minute: 10
  - name: image-generate-route
    paths:
      - /kong/image/generate
    service: image-generate-service
    plugins:
      - name: basic-auth
        config:
          hide_credentials: true
      # - name: rate-limiting
      #   config:
      #     minute: 10
  - name: image-query-route
    paths:
      - /kong/image/query
    service: image-query-service
    plugins:
      - name: basic-auth
        config:
          hide_credentials: true
      # - name: rate-limiting
      #   config:
      #     minute: 10
  - name: image-inspect-route
    paths:
      - /kong/image/inspect
    service: image-query-service
    plugins:
      - name: basic-auth
        config:
          hide_credentials: true
      # - name: rate-limiting
      #   config:
      #     minute: 10

consumers:
  - username: AElf-dev

basicauth_credentials:
  - consumer: AElf-dev
    username: aelf
    password: aelf2024
